################################
# ISSUE TEMPLATE CONFIGURATION #
################################
#                              #
# Currently blank issues are   #
# not permitted on favor of    #
# the form models.             #
################################

blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/users/335813464079728650
    about: You can contact me directly if you want to.
